### ISSUE TITLE
Using files section in kind: "ClickHouseInstallation" causes panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by blafry** [Altinity/clickhouse-operator#261]
Hi!
Using the latest version I encountered the following problem, it does not occur in version 0.8.0.

Steps to reproduce:

- install clickhouse-operator in version 0.9.0
- apply ClickHouseInstallation attached below
```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"

spec:
  configuration:
    files:
      dict1.xml: |
        <yandex>
            <!-- ref to file /etc/clickhouse-data/config.d/source1.csv -->
        </yandex>
```

- check clickhouse-operator logs
```
I0218 14:45:43.026586       1 creator.go:57] createServiceChi(clickhouse/clickhouse-simple-01)
I0218 14:45:43.026682       1 creator.go:60] Reconcile Service clickhouse/clickhouse-simple-01
I0218 14:45:43.026751       1 creator.go:64] Update Service clickhouse/clickhouse-simple-01
E0218 14:45:43.045957       1 runtime.go:69] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/map_faststr.go:204
/go/src/github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_settings.go:92
/go/src/github.com/altinity/clickhouse-operator/pkg/model/ch_config.go:69
/go/src/github.com/altinity/clickhouse-operator/pkg/model/ch_config_sections.go:52
/go/src/github.com/altinity/clickhouse-operator/pkg/model/creator.go:240
/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/worker.go:254
/go/src/github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_chi.go:397
/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/worker.go:233
/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/worker.go:173
/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/worker.go:125
/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/worker.go:56
/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/controller.go:389
/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 124 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1224180, 0x15533e0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1.Settings.GetStringMap(0xc0003d7d40, 0xc0003e2000)
	/go/src/github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_settings.go:92 +0x120
github.com/altinity/clickhouse-operator/pkg/model.(*ClickHouseConfigGenerator).GetFiles(...)
	/go/src/github.com/altinity/clickhouse-operator/pkg/model/ch_config.go:69
github.com/altinity/clickhouse-operator/pkg/model.(*configSections).CreateConfigsCommon(0xc0007c7a00)
	/go/src/github.com/altinity/clickhouse-operator/pkg/model/ch_config_sections.go:52 +0xcd
github.com/altinity/clickhouse-operator/pkg/model.(*Creator).CreateConfigMapChiCommon(0xc000819a10, 0xc0002521e0)
	/go/src/github.com/altinity/clickhouse-operator/pkg/model/creator.go:240 +0x33
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).reconcileChi(0xc00068cdc0, 0xc00065e000, 0xc000190e00, 0x20)
	/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/worker.go:254 +0x69
github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1.(*ClickHouseInstallation).WalkTillError(0xc00065e000, 0xc000757990, 0xc000757980, 0xc000757970, 0xc000757960, 0xc000190e00, 0x2031e98)
	/go/src/github.com/altinity/clickhouse-operator/pkg/apis/clickhouse.altinity.com/v1/type_chi.go:397 +0x3d
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).reconcile(0xc00068cdc0, 0xc00065e000, 0x0, 0x0)
	/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/worker.go:233 +0x283
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).updateChi(0xc00068cdc0, 0xc000683c00, 0xc00065e000, 0x6, 0x1390e4d)
	/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/worker.go:173 +0x6e5
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).addChi(0xc00068cdc0, 0xc000026e00, 0xc00051dd70, 0xc00051dcd0)
	/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/worker.go:125 +0x1e2
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*worker).processItem(0xc00068cdc0, 0x116f660, 0xc000369ba0, 0xc00037cb00, 0xc0004fce88)
	/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/worker.go:56 +0x8dd
github.com/altinity/clickhouse-operator/pkg/controller/chi.(*Controller).runWorker(0xc0001381e0)
	/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/controller.go:389 +0x1fb
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000760400)
	/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000760400, 0x3b9aca00, 0x0, 0x46f201, 0xc000427e00)
	/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000760400, 0x3b9aca00, 0xc000427e00)
	/go/src/github.com/altinity/clickhouse-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/altinity/clickhouse-operator/pkg/controller/chi.(*Controller).Run
	/go/src/github.com/altinity/clickhouse-operator/pkg/controller/chi/controller.go:370 +0x213
```

**Comment by sunsingerus** [comment]
Thanks for notification, we'll take a look

**Comment by sunsingerus** [comment]
@blafry please check fix in [0.9.1 branch](https://github.com/Altinity/clickhouse-operator/tree/0.9.1)

**Comment by blafry** [comment]
@sunsingerus now it works like a charm. Thank you.

**Comment by alex-zaitsev** [comment]
https://github.com/Altinity/clickhouse-operator/releases/tag/0.9.1
