### ISSUE TITLE
clickhouse_driver.errors.NetworkError

### ISSUE THREAD

**Issue by xgengsjc2021** [Altinity/clickhouse-operator#963]
Hi, 

I had a sentry which used an internal CH. Since I had built a standalone CH by the operator, I tried to make sentry to connect to this new independent CH but failed. 

My CH has 3 shards with 2 replicas respectively. An internal LB also was created when I built the CH. I set up sentry to connect this external CH, got the error below:

service of CH
```
kubectl -n clickhouse get svc
NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP                                                                             PORT(S)                         AGE
chi-ch-install-ch-cluster-shard0-0   ClusterIP      None             <none>                                                                                  8123/TCP,9000/TCP,9009/TCP      61m
chi-ch-install-ch-cluster-shard0-1   ClusterIP      None             <none>                                                                                  8123/TCP,9000/TCP,9009/TCP      61m
chi-ch-install-ch-cluster-shard1-0   ClusterIP      None             <none>                                                                                  8123/TCP,9000/TCP,9009/TCP      61m
chi-ch-install-ch-cluster-shard1-1   ClusterIP      None             <none>                                                                                  8123/TCP,9000/TCP,9009/TCP      60m
chi-ch-install-ch-cluster-shard2-0   ClusterIP      None             <none>                                                                                  8123/TCP,9000/TCP,9009/TCP      60m
chi-ch-install-ch-cluster-shard2-1   ClusterIP      None             <none>                                                                                  8123/TCP,9000/TCP,9009/TCP      60m
service-ch-install                   LoadBalancer   172.20.209.245   xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com  8123:32197/TCP,9000:31320/TCP   62m
```

my sentry setting of CH
```
externalClickhouse:
  host: "xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com"
  username: clickhouse_operator
  password: clickhouse_operator_password
  singleNode: false
  clusterName: ch-cluster
```

```

2022-06-24 17:52:25,408 Attempting to connect to Clickhouse cluster xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000 (attempt 0)
2022-06-24 17:52:25,412 Connecting. Database: default. User: clickhouse_operator
2022-06-24 17:52:25,412 Connecting to xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000
2022-06-24 17:52:25,418 Connected to ClickHouse server version 22.3.7, revision: 54455
2022-06-24 17:52:25,419 Query: SELECT version()
2022-06-24 17:52:25,419 Block "" send time: 0.000049
2022-06-24 17:52:25,424 Query: SELECT group, migration_id, status FROM migrations_dist FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions')
2022-06-24 17:52:25,424 Block "" send time: 0.000038
2022-06-24 17:52:25,429 Running migration: 0001_migrations
2022-06-24 17:52:25,429 Connecting. Database: default. User: clickhouse_operator
2022-06-24 17:52:25,429 Connecting to xxxxxxxxxxxxx.elb.us-west-1.amazonaws.com:9000
2022-06-24 17:52:25,432 Connected to ClickHouse server version 22.3.7, revision: 54455
2022-06-24 17:52:25,433 Query: select host_name, port, shard_num, replica_num from system.clusters where cluster='ch-cluster'
2022-06-24 17:52:25,433 Block "" send time: 0.000041
2022-06-24 17:52:25,450 Connecting. Database: default. User: clickhouse_operator
2022-06-24 17:52:25,450 Connecting to chi-ch-install-ch-cluster-shard0-0:9000
2022-06-24 17:52:25,454 Failed to connect to chi-ch-install-ch-cluster-shard0-0:9000
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 319, in connect
    return self._init_connection(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 283, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 235, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

2022-06-24 17:52:25,555 Connecting. Database: default. User: clickhouse_operator
2022-06-24 17:52:25,555 Connecting to chi-ch-install-ch-cluster-shard0-0:9000
2022-06-24 17:52:25,558 Failed to connect to chi-ch-install-ch-cluster-shard0-0:9000
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 319, in connect
    return self._init_connection(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 283, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 235, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

clickhouse_driver.errors.NetworkError: Code: 210. Name or service not known (chi-ch-install-ch-cluster-shard0-0:9000)
```

**Comment by Slach** [comment]
Do you install sentry inside the same kubernetes cluster or  sentry setup outside kubernetes?

**Comment by Slach** [comment]
try  to use `singleNode: true`

but you shall replace manually sentry tables as `Engine=Distributed` with underlying Engine=ReplicatedMergeTree
look https://clickhouse.com/docs/en/engines/table-engines/special/distributed/ for details
