### ISSUE TITLE
zookeeper Liveness probe failed, Readiness probe failed, Back-off restarting failed container

### ISSUE THREAD

**Issue by xgengsjc2021** [Altinity/clickhouse-operator#979]
Hi,

After deployment for a few days, I realized that one of zookeeper pods is in crash loop. I noticed that it has Liveness probe failed and Readiness probe failed. 

Got some error from pods:
```
2022-07-19 05:49:37,977 [myid:] - WARN  [QuorumConnectionThread-[myid=2]-3:o.a.z.s.q.QuorumCnxManager@401] - Cannot open channel to 1 at election address zookeeper-0.zookeepers.zoons.svc.cluster.local:3888
java.net.UnknownHostException: zookeeper-0.zookeepers.zoons.svc.cluster.local
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.initiateConnection(QuorumCnxManager.java:384)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$QuorumConnectionReqThread.run(QuorumCnxManager.java:458)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

```
2022-07-19 05:49:18,917 [myid:] - WARN  [RecvWorker:2:o.a.z.s.q.QuorumCnxManager$RecvWorker@1408] - Interrupting SendWorker thread from RecvWorker. sid: 2. myId: 3
2022-07-19 05:49:18,917 [myid:] - WARN  [SendWorker:2:o.a.z.s.q.QuorumCnxManager$SendWorker@1288] - Interrupted while waiting for message on queue
java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(Unknown Source)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
	at org.apache.zookeeper.util.CircularBlockingQueue.poll(CircularBlockingQueue.java:105)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.pollSendQueue(QuorumCnxManager.java:1453)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.access$900(QuorumCnxManager.java:99)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$SendWorker.run(QuorumCnxManager.java:1277)
2022-07-19 05:49:18,918 [myid:] - WARN  [SendWorker:2:o.a.z.s.q.QuorumCnxManager$SendWorker@1300] - Send worker leaving thread id 2 my id = 3
2022-07-19 05:49:24,055 [myid:] - WARN  [NIOWorkerThread-1:o.a.z.s.NIOServerCnxn@380] - Close of session 0x0
java.io.IOException: ZooKeeperServer not running
	at org.apache.zookeeper.server.NIOServerCnxn.readLength(NIOServerCnxn.java:554)
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:339)
	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:508)
	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:153)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by xgengsjc2021** [comment]
btw, my zookeeper has limited cpu/memory. Not sure if this is related to the resource. 
```
resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "0.5"
```
2: when I installed the zookeeper, I am using aws efs as storage class. And removed 
```
chown -Rv zookeeper "$ZOO_DATA_DIR" "$ZOO_DATA_LOG_DIR" "$ZOO_LOG_DIR" "$ZOO_CONF_DIR" &&
```
Since, https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/300

**Comment by alex-zaitsev** [comment]
Looks like not enough RAM for ZK.

**Comment by xgengsjc2021** [comment]
@alex-zaitsev Usually, what's the least CPU/Mem setting for the clickhouse installation?
